### ISSUE TITLE
Create WordPress.org assets for "Pronamic Pay with Rabo Smart Pay for WooCommerce" plugin

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/pronamic-pay-with-rabo-smart-pay-for-woocommerce#1]
Can you make WordPress.org assets for this plugin @kjtolsma?
https://github.com/pronamic/pronamic-pay-with-rabo-smart-pay-for-woocommerce/tree/main/.wordpress-org

**Comment by kjtolsma** [comment]
Updated https://github.com/pronamic/pronamic-pay-with-rabo-smart-pay-for-woocommerce/commit/df0fbfa473af34d6e10aca5ec100b2d9a6ea75a0.
