### ISSUE TITLE
Improve screenshots

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/pronamic-pay-with-rabo-smart-pay-for-woocommerce#5]
Screenshots mention Mollie, needs to be improved:

https://github.com/pronamic/pronamic-pay-with-rabo-smart-pay-for-woocommerce/tree/878d2d2e761c32ec1cfd7924f439ada48c61b349/.wordpress-org

_Reported by @rvdsteege_

I also noticed that https://wordpress.org/plugins/icon-block/ is using an animated GIF, maybe that is also something for Pronamic Pay.

WooCommerce alse frame the browser screenshots: https://wordpress.org/plugins/woocommerce/, this way there can also be a title above and the screenshots are more uniform.

**Comment by LeoOosterloo** [comment]
For now I made recreated the current screenshots with versions for Rabobank.

![rabosmartpay_pronamic_gateway](https://github.com/pronamic/pronamic-pay-with-rabo-smart-pay-for-woocommerce/assets/610613/95fd352c-1823-457e-bf53-3ab4a60b4c15)

![rabosmartpay_new_pronamic_gateway](https://github.com/pronamic/pronamic-pay-with-rabo-smart-pay-for-woocommerce/assets/610613/cf99eed0-fb8e-4a76-999b-79b29bb66e1b)

Animated gifs for the screenshots/casts could be useful to show the usability.
